spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disneyalkemy?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        format_sql: false
    database: MYSQL
    show-sql: true
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
---